apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/docker/db/
    server: 18.191.104.43
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-assets-pv
  labels:
    type: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/docker/static/assets/
    server: 18.191.104.43
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-media-pv
  labels:
    type: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/docker/static/media/
    server: 18.191.104.43
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    type: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/docker/logs
    server: 18.191.104.43
  persistentVolumeReclaimPolicy: Retain
