apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: seakube-dev
  labels:
    app: sea-app
spec:
  selector:
    matchLabels:
      app: sea-app
  template:
    metadata:
      labels:
        app: sea-app
    spec:
      containers:
      - name: seakube-app
        image: seakube:1.0
        ports:
        - containerPort: 8000






