apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    pod: app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-assets-pvc
  labels:
    type: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: static-assets-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-media-pvc
  labels:
    type: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: static-media-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  labels:
    type: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: logs-pv

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: app
  labels:
    name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: app
  template:
    metadata:
      labels:
        pod: app
    spec:
      containers:
        - name: app
          image: roseth/thorkube:1.1
          ports:
          - containerPort: 8000
          env:
            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  name: env-secrets
                  key: DATABASE_USER

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-secrets
                  key: DATABASE_HOST
          
          volumeMounts:
            - name: static-assets
              mountPath: /app/assets
            - name: static-media
              mountPath: /app/media
            - name: logs
              mountPath: /app/pronto_dashboard/logs

      volumes:
        - name: static-assets
          persistentVolumeClaim:
            claimName: static-assets-pvc
        - name: static-media
          persistentVolumeClaim:
            claimName: static-media-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc